Update main CI config

diff --git a/.github/workflows/main_ci.yml b/.github/workflows/main_ci.yml
--- a/.github/workflows/main_ci.yml
+++ b/.github/workflows/main_ci.yml
@@ -78,7 +78,7 @@ jobs:
   #             body: body
   #           })
 
-  bazel-test:
+  bazel-build-and-test:
     if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.comment.body, 'recheck')
 
     # The type of runner that the job will run on
@@ -92,39 +92,40 @@ jobs:
       - name: Setup bazel
         uses: bazelbuild/setup-bazelisk@v3
         
-      - name: gcc debug build
-        run: bazel build --config=gcc9 --config=c++17 --config=debug //... -- -//bazel/...
-        
+      - name: clang debug build
+        run: bazel build --config=clang14 --config=c++17 --config=debug --verbose_failures --subcommands //...
+
       - name: gcc test fastbuild
-        run: bazel test --config=gcc9 --config=c++17 --compilation_mode=fastbuild --cache_test_results=no --test_output=all //... -- -//bazel/...
+        run: bazel test --config=gcc9 --config=c++17 --compilation_mode=fastbuild --cache_test_results=no --test_output=all --verbose_failures --subcommands //...
 
-      - name: clang test fastbuild
-        run: bazel test --config=clang14 --config=c++17 --compilation_mode=fastbuild --cache_test_results=no --test_output=all //... -- -//bazel/...
+  cpp-lint:    
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout to PR branch
+        id: pr_branch_data
+        if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.issue.labels.*.name, 'check')
+        uses: actions/checkout@v4
 
+      - name: Setup linter
+        if: steps.pr_branch_data.outcome == 'success'
+        uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: 'file'  # Use .clang-format config file
+          tidy-checks: '' # Use .clang-tidy config file
+          # only 'update' a single comment in a pull request's thread.
+          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
 
-  # cpp-lint:    
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout to PR branch
-  #       id: pr_branch_data
-  #       if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.issue.labels.*.name, 'check')
-  #       uses: actions/checkout@v3
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed > 0
+        run: |
+          echo "Some files failed the linting checks!"
+        # for actual deployment
+        # run: exit 1
 
-  #     - name: Setup linter
-  #       if: steps.pr_branch_data.outcome == 'success'
-  #       uses: cpp-linter/cpp-linter-action@v1
-  #       id: linter
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       with:
-  #         style: file
-
-  #     - name: Fail fast?!
-  #       if: steps.linter.outputs.checks-failed > 0
-  #       run: |
-  #         echo "Some files failed the linting checks!"
-  #       # for actual deployment
-  #       # run: exit 1
+      
 
   print-context:
     runs-on: ubuntu-latest
