Print clang version for ubuntu latest

diff --git a/.github/workflows/main_ci.yml b/.github/workflows/main_ci.yml
--- a/.github/workflows/main_ci.yml
+++ b/.github/workflows/main_ci.yml
@@ -16,116 +16,116 @@ on:
 jobs:
 
   # This workflow contains a multiple jobs
-  bazel-build:
-    if: (github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'check') && contains(github.event.comment.body, 'recheck')) || contains(github.event.pull_request.labels.*.name, 'check')
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  # bazel-build:
+  #   if: (github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'check') && contains(github.event.comment.body, 'recheck')) || contains(github.event.pull_request.labels.*.name, 'check')
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      - name: Get PR branch
-        uses: xt0rted/pull-request-comment-branch@v2
-        id: comment-branch
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     - name: Get PR branch
+  #       uses: xt0rted/pull-request-comment-branch@v2
+  #       id: comment-branch
 
-      - name: Set latest commit status as pending
-        uses: myrotvorets/set-commit-status-action@master
-        with:
-          sha: ${{ steps.comment-branch.outputs.head_sha }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          status: pending
+  #     - name: Set latest commit status as pending
+  #       uses: myrotvorets/set-commit-status-action@master
+  #       with:
+  #         sha: ${{ steps.comment-branch.outputs.head_sha }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         status: pending
 
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Checkout to PR branch
-        id: checkout-branch
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ steps.comment-branch.outputs.head_ref }}
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - name: Checkout to PR branch
+  #       id: checkout-branch
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: ${{ steps.comment-branch.outputs.head_ref }}
 
-      - name: Setup Node.js 16
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16
+  #     - name: Setup Node.js 16
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16
 
-      - name: Setup Bazel
-        uses: bazelbuild/setup-bazelisk@v2
+  #     - name: Setup Bazel
+  #       uses: bazelbuild/setup-bazelisk@v2
 
-      - name: Build
-        id: bazel_build
-        run: bazel build --cxxopt="-std=c++17" //...
+  #     - name: Build
+  #       id: bazel_build
+  #       run: bazel build --cxxopt="-std=c++17" //...
 
-      - name: Set latest commit status as ${{ job.status }}
-        uses: myrotvorets/set-commit-status-action@master
-        if: always()
-        with:
-          sha: ${{ steps.comment-branch.outputs.head_sha }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ job.status }}
+  #     - name: Set latest commit status as ${{ job.status }}
+  #       uses: myrotvorets/set-commit-status-action@master
+  #       if: always()
+  #       with:
+  #         sha: ${{ steps.comment-branch.outputs.head_sha }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         status: ${{ job.status }}
 
-      - name: Comment status of job on PR
-        uses: actions/github-script@v6
-        if: ${{ job.status }} == failed()
-        with:
-          script: |
-            const name = '${{ github.workflow   }}';
-            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
-            const success = '${{ job.status }}' === 'success';
-            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;
+  #     - name: Comment status of job on PR
+  #       uses: actions/github-script@v6
+  #       if: ${{ job.status }} == failed()
+  #       with:
+  #         script: |
+  #           const name = '${{ github.workflow   }}';
+  #           const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
+  #           const success = '${{ job.status }}' === 'success';
+  #           const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;
 
-            await github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: body
-            })
+  #           await github.rest.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: body
+  #           })
 
-  bazel-test:
-    if: contains(github.event.pull_request.labels.*.name, 'check')
+  # bazel-test:
+  #   if: contains(github.event.pull_request.labels.*.name, 'check')
 
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      - name: Checkout to PR branch
-        uses: actions/checkout@v3
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     - name: Checkout to PR branch
+  #       uses: actions/checkout@v3
 
-      - name: Setup bazel
-        uses: bazelbuild/setup-bazelisk@v2
+  #     - name: Setup bazel
+  #       uses: bazelbuild/setup-bazelisk@v2
         
-      - name: optimize fastbuild
-        run: bazel test --cxxopt="-std=c++17" -c opt --cache_test_results=no --test_output=all //...
+  #     - name: optimize fastbuild
+  #       run: bazel test --cxxopt="-std=c++17" -c opt --cache_test_results=no --test_output=all //...
 
-      - name: debug build
-        run: bazel test --cxxopt="-std=c++17" --copt="-ggdb" -c dbg --copt="-O0" --test_output=all --nocache_test_results //...
+  #     - name: debug build
+  #       run: bazel test --cxxopt="-std=c++17" --copt="-ggdb" -c dbg --copt="-O0" --test_output=all --nocache_test_results //...
 
-  cpp-lint:    
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout to PR branch
-        id: pr_branch_data
-        if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.issue.labels.*.name, 'check')
-        uses: actions/checkout@v3
+  # cpp-lint:    
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout to PR branch
+  #       id: pr_branch_data
+  #       if: contains(github.event.pull_request.labels.*.name, 'check') || contains(github.event.issue.labels.*.name, 'check')
+  #       uses: actions/checkout@v3
 
-      - name: Setup linter
-        if: steps.pr_branch_data.outcome == 'success'
-        uses: cpp-linter/cpp-linter-action@v1
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          style: file
+  #     - name: Setup linter
+  #       if: steps.pr_branch_data.outcome == 'success'
+  #       uses: cpp-linter/cpp-linter-action@v1
+  #       id: linter
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       with:
+  #         style: file
 
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: |
-          echo "Some files failed the linting checks!"
-        # for actual deployment
-        # run: exit 1
+  #     - name: Fail fast?!
+  #       if: steps.linter.outputs.checks-failed > 0
+  #       run: |
+  #         echo "Some files failed the linting checks!"
+  #       # for actual deployment
+  #       # run: exit 1
 
-  print_context:
+  print-context-and-clang-version:
     runs-on: ubuntu-latest
     steps:
       - env:
           EVENT_CONTEXT: ${{ toJSON(github.event) }}
         run: |
-          echo $EVENT_CONTEXT
+          echo $EVENT_CONTEXT && clang --version
